blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BlogListView, BlogItemView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('view/<int:pk>/', BlogItemView.as_view(), name='read'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),

]

evrone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from front.views import login, logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models


class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    preview = models.ImageField(upload_to='blog', verbose_name='Изображение для превью')
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    intro = models.TextField(blank=True, null=True, verbose_name='Вступление')
    body = models.TextField(verbose_name='Содержимое')

    public_after_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата отложенной пуликации')
    public_date = models.DateTimeField(verbose_name='Дата пуликации')

    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'записи'
        ordering = ('-public_date',)

front/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms

from blog.models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ('deleted',)

    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

front/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DeleteView, UpdateView, CreateView, DetailView

from blog.forms import ArticleForm
from blog.models import Article


class BlogListView(ListView):
    model = Article


class BlogItemView(DetailView):
    model = Article

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(BlogItemView, self).dispatch(*args, **kwargs)


class BlogCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('blog:blog')

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(BlogCreateView, self).dispatch(*args, **kwargs)


class BlogUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('blog:blog')

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(BlogUpdateView, self).dispatch(*args, **kwargs)


class BlogDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('ordersapp:orders_list')

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(BlogDeleteView, self).dispatch(*args, **kwargs)

front/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib import auth
from front.forms import UserLoginForm


def login(request):
    login_form = UserLoginForm(data=request.POST or None)

    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('blog:blog'))

    return render(request, 'front/login.html')


def logout(request):
    return HttpResponseRedirect(reverse('blog:blog'))

blog/templates/blog/article_confirm_delete.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <div class="row">
    <div class="col-12 form-group">
        <div class="h1">Уверены, что хотите удалить?</div>
        {{ object.title }}
        <form action="{% url 'blog:delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-info text-white mt-4">
            <a href="{% url 'blog:blog' %}">отмена</a>
        </button>
    </div>
    </div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="row">
<div class="col-12">
    <h1 class="text-center">{{ object.title }}</h1>
    <p>
        {{ object.body }}
    </p>
</div>
</div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="row">
<div class="col-12">
    <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <p>
                {{ field.errors.as_ul }}
                <label>{{ field.label }}</label>
                {% if field.name == 'public_after_date' or field.name == 'public_date' %}
                    <input class="form-control" type="datetime-local" name="{{ field.name }}" id="id_{{ field.name }}" value="{{ field.value|date:'Y-m-d\TH:i' }}" />
                {% else %}
                    {{ field }}
                {% endif %}
            </p>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
                {% if object %}
                    Сохранить
                {% else %}
                    Добавить
                {% endif %}
            </button>
            <a href="{% url 'blog:blog' %}" class="btn btn-warning">
                Отмена
            </a>
            <a href="{% url 'blog:delete' object.pk %}" class="btn btn-danger right">
                Удалить
            </a>
        </div>
    </form>
</div>
</div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="row">
{% for object in object_list %}
    <div class="col-md-4">
      <div class="card mb-4 box-shadow">
        <img src="/media/{{ object.preview }}" class="card-img-top">
        <div class="card-body">
          <p class="card-text">{{ object.title }}</p>
          <p class="card-text">{{ object.intro }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <a href="{% url 'blog:read' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                {% if user.is_superuser %}
              <a type="button" href="{% url 'blog:update' object.pk %}" class="btn btn-sm btn-outline-secondary">Edit</a>
                {% endif %}
            </div>
            <small class="text-muted">{{ object.public_date|date:"d-m-Y" }}</small>
          </div>
        </div>
      </div>
    </div>
{% endfor %}
</div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Test Project</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <ul class="list-unstyled">
                  {% if user.is_authenticated %}
                      <li><a href="{% url 'logout' %}" class="text-white">Logout</a></li>
                  {% else %}
                      <li><a href="{% url 'login' %}" class="text-white">Login</a></li>
                  {% endif %}
                {% if user.is_superuser %}
                    <li><a href="{% url 'blog:create' %}" class="text-white">Add article</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'blog:blog' %}" class="navbar-brand d-flex align-items-center">
            <strong>Blog</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Album example</h1>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}

        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

front/templates/front/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Test Project</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post">
      {% csrf_token %}
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="inputEmail" class="sr-only">Username</label>
      <input type="text" id="inputEmail" class="form-control" placeholder="Username" name="username" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; {% now 'Y' %}</p>
    </form>
  </body>
</html>